{% set name = "django-countries" %}
{% set version = "7.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-countries-{{ version }}.tar.gz
  sha256: 0df6d34193667c2343da8935cbfb8a2bd4fb0c97baf01ac10db4628ba1557a82

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - django >=1.11,<3.0

test:
  imports:
    - django_countries
    - django_countries.graphql
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/SmileyChris/django-countries/
  summary: Provides a country field for Django models.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mxr-conda
