{% set name = "django-countries" %}
{% set version = "7.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django-countries-{{ version }}.tar.gz
  sha256: c772d4e3e54afcc5f97a018544e96f246c6d9f1db51898ab0c15cd57e19437cf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=48
    - wheel >=0.29.0
    - pip
  run:
    - python >={{ python_min }}
    - django >=3.2,<5.0
    - asgiref
    - typing-extensions

test:
  imports:
    - django_countries
    - django_countries.graphql
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/SmileyChris/django-countries/
  summary: Provides a country field for Django models.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mxr-conda
    - rxm7706
